version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    build: .
    container_name: lester
    ports:
      - "50051:50051"
    depends_on:
      rabbitmq:
        condition: service_healthy
