// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: proto/heist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PhaseStatus_Status int32

const (
	PhaseStatus_IN_PROGESS      PhaseStatus_Status = 0
	PhaseStatus_SUCCESS         PhaseStatus_Status = 1
	PhaseStatus_FAILURE         PhaseStatus_Status = 2
	PhaseStatus_AWAITING_ORDERS PhaseStatus_Status = 3
)

// Enum value maps for PhaseStatus_Status.
var (
	PhaseStatus_Status_name = map[int32]string{
		0: "IN_PROGESS",
		1: "SUCCESS",
		2: "FAILURE",
		3: "AWAITING_ORDERS",
	}
	PhaseStatus_Status_value = map[string]int32{
		"IN_PROGESS":      0,
		"SUCCESS":         1,
		"FAILURE":         2,
		"AWAITING_ORDERS": 3,
	}
)

func (x PhaseStatus_Status) Enum() *PhaseStatus_Status {
	p := new(PhaseStatus_Status)
	*p = x
	return p
}

func (x PhaseStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhaseStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_heist_proto_enumTypes[0].Descriptor()
}

func (PhaseStatus_Status) Type() protoreflect.EnumType {
	return &file_proto_heist_proto_enumTypes[0]
}

func (x PhaseStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhaseStatus_Status.Descriptor instead.
func (PhaseStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{5, 0}
}

type NotificationCommand_Command int32

const (
	NotificationCommand_START NotificationCommand_Command = 0
	NotificationCommand_STOP  NotificationCommand_Command = 1
)

// Enum value maps for NotificationCommand_Command.
var (
	NotificationCommand_Command_name = map[int32]string{
		0: "START",
		1: "STOP",
	}
	NotificationCommand_Command_value = map[string]int32{
		"START": 0,
		"STOP":  1,
	}
)

func (x NotificationCommand_Command) Enum() *NotificationCommand_Command {
	p := new(NotificationCommand_Command)
	*p = x
	return p
}

func (x NotificationCommand_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationCommand_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_heist_proto_enumTypes[1].Descriptor()
}

func (NotificationCommand_Command) Type() protoreflect.EnumType {
	return &file_proto_heist_proto_enumTypes[1]
}

func (x NotificationCommand_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationCommand_Command.Descriptor instead.
func (NotificationCommand_Command) EnumDescriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{7, 0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_heist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{0}
}

type HeistOffer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Loot            int32                  `protobuf:"varint,1,opt,name=loot,proto3" json:"loot,omitempty"`
	FranklinSuccess int32                  `protobuf:"varint,2,opt,name=franklin_success,json=franklinSuccess,proto3" json:"franklin_success,omitempty"`
	TrevorSuccess   int32                  `protobuf:"varint,3,opt,name=trevor_success,json=trevorSuccess,proto3" json:"trevor_success,omitempty"`
	PoliceRisk      int32                  `protobuf:"varint,4,opt,name=police_risk,json=policeRisk,proto3" json:"police_risk,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeistOffer) Reset() {
	*x = HeistOffer{}
	mi := &file_proto_heist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeistOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeistOffer) ProtoMessage() {}

func (x *HeistOffer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeistOffer.ProtoReflect.Descriptor instead.
func (*HeistOffer) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{1}
}

func (x *HeistOffer) GetLoot() int32 {
	if x != nil {
		return x.Loot
	}
	return 0
}

func (x *HeistOffer) GetFranklinSuccess() int32 {
	if x != nil {
		return x.FranklinSuccess
	}
	return 0
}

func (x *HeistOffer) GetTrevorSuccess() int32 {
	if x != nil {
		return x.TrevorSuccess
	}
	return 0
}

func (x *HeistOffer) GetPoliceRisk() int32 {
	if x != nil {
		return x.PoliceRisk
	}
	return 0
}

type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_proto_heist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{2}
}

func (x *Decision) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type BasicMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicMessage) Reset() {
	*x = BasicMessage{}
	mi := &file_proto_heist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicMessage) ProtoMessage() {}

func (x *BasicMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicMessage.ProtoReflect.Descriptor instead.
func (*BasicMessage) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{3}
}

func (x *BasicMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PhaseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseResult) Reset() {
	*x = PhaseResult{}
	mi := &file_proto_heist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseResult) ProtoMessage() {}

func (x *PhaseResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseResult.ProtoReflect.Descriptor instead.
func (*PhaseResult) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{4}
}

func (x *PhaseResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PhaseStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PhaseStatus_Status     `protobuf:"varint,1,opt,name=status,proto3,enum=heist.PhaseStatus_Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ExtraMoney    int32                  `protobuf:"varint,3,opt,name=extraMoney,proto3" json:"extraMoney,omitempty"`
	TotalLoot     int32                  `protobuf:"varint,4,opt,name=totalLoot,proto3" json:"totalLoot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseStatus) Reset() {
	*x = PhaseStatus{}
	mi := &file_proto_heist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseStatus) ProtoMessage() {}

func (x *PhaseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseStatus.ProtoReflect.Descriptor instead.
func (*PhaseStatus) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{5}
}

func (x *PhaseStatus) GetStatus() PhaseStatus_Status {
	if x != nil {
		return x.Status
	}
	return PhaseStatus_IN_PROGESS
}

func (x *PhaseStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PhaseStatus) GetExtraMoney() int32 {
	if x != nil {
		return x.ExtraMoney
	}
	return 0
}

func (x *PhaseStatus) GetTotalLoot() int32 {
	if x != nil {
		return x.TotalLoot
	}
	return 0
}

type DistractionDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TurnsNeeded   int32                  `protobuf:"varint,1,opt,name=turns_needed,json=turnsNeeded,proto3" json:"turns_needed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistractionDetails) Reset() {
	*x = DistractionDetails{}
	mi := &file_proto_heist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistractionDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistractionDetails) ProtoMessage() {}

func (x *DistractionDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistractionDetails.ProtoReflect.Descriptor instead.
func (*DistractionDetails) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{6}
}

func (x *DistractionDetails) GetTurnsNeeded() int32 {
	if x != nil {
		return x.TurnsNeeded
	}
	return 0
}

type NotificationCommand struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Command       NotificationCommand_Command `protobuf:"varint,1,opt,name=command,proto3,enum=heist.NotificationCommand_Command" json:"command,omitempty"`
	Frequency     int32                       `protobuf:"varint,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationCommand) Reset() {
	*x = NotificationCommand{}
	mi := &file_proto_heist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationCommand) ProtoMessage() {}

func (x *NotificationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationCommand.ProtoReflect.Descriptor instead.
func (*NotificationCommand) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{7}
}

func (x *NotificationCommand) GetCommand() NotificationCommand_Command {
	if x != nil {
		return x.Command
	}
	return NotificationCommand_START
}

func (x *NotificationCommand) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type HitDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TurnsNeeded   int32                  `protobuf:"varint,1,opt,name=turns_needed,json=turnsNeeded,proto3" json:"turns_needed,omitempty"`
	Loot          int32                  `protobuf:"varint,2,opt,name=loot,proto3" json:"loot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitDetails) Reset() {
	*x = HitDetails{}
	mi := &file_proto_heist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitDetails) ProtoMessage() {}

func (x *HitDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitDetails.ProtoReflect.Descriptor instead.
func (*HitDetails) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{8}
}

func (x *HitDetails) GetTurnsNeeded() int32 {
	if x != nil {
		return x.TurnsNeeded
	}
	return 0
}

func (x *HitDetails) GetLoot() int32 {
	if x != nil {
		return x.Loot
	}
	return 0
}

type LootDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loot          int32                  `protobuf:"varint,1,opt,name=loot,proto3" json:"loot,omitempty"`
	ExtraMoney    int32                  `protobuf:"varint,2,opt,name=extra_money,json=extraMoney,proto3" json:"extra_money,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LootDetails) Reset() {
	*x = LootDetails{}
	mi := &file_proto_heist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LootDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LootDetails) ProtoMessage() {}

func (x *LootDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LootDetails.ProtoReflect.Descriptor instead.
func (*LootDetails) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{9}
}

func (x *LootDetails) GetLoot() int32 {
	if x != nil {
		return x.Loot
	}
	return 0
}

func (x *LootDetails) GetExtraMoney() int32 {
	if x != nil {
		return x.ExtraMoney
	}
	return 0
}

type CutDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loot          int32                  `protobuf:"varint,1,opt,name=loot,proto3" json:"loot,omitempty"`
	ExtraMoeny    int32                  `protobuf:"varint,2,opt,name=extra_moeny,json=extraMoeny,proto3" json:"extra_moeny,omitempty"`
	ReceivedCut   int32                  `protobuf:"varint,3,opt,name=received_cut,json=receivedCut,proto3" json:"received_cut,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CutDetails) Reset() {
	*x = CutDetails{}
	mi := &file_proto_heist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CutDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutDetails) ProtoMessage() {}

func (x *CutDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutDetails.ProtoReflect.Descriptor instead.
func (*CutDetails) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{10}
}

func (x *CutDetails) GetLoot() int32 {
	if x != nil {
		return x.Loot
	}
	return 0
}

func (x *CutDetails) GetExtraMoeny() int32 {
	if x != nil {
		return x.ExtraMoeny
	}
	return 0
}

func (x *CutDetails) GetReceivedCut() int32 {
	if x != nil {
		return x.ReceivedCut
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_heist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_heist_proto_rawDescGZIP(), []int{11}
}

func (x *Ack) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_heist_proto protoreflect.FileDescriptor

const file_proto_heist_proto_rawDesc = "" +
	"\n" +
	"\x11proto/heist.proto\x12\x05heist\"\a\n" +
	"\x05Empty\"\x93\x01\n" +
	"\n" +
	"HeistOffer\x12\x12\n" +
	"\x04loot\x18\x01 \x01(\x05R\x04loot\x12)\n" +
	"\x10franklin_success\x18\x02 \x01(\x05R\x0ffranklinSuccess\x12%\n" +
	"\x0etrevor_success\x18\x03 \x01(\x05R\rtrevorSuccess\x12\x1f\n" +
	"\vpolice_risk\x18\x04 \x01(\x05R\n" +
	"policeRisk\"&\n" +
	"\bDecision\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"(\n" +
	"\fBasicMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"'\n" +
	"\vPhaseResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xe1\x01\n" +
	"\vPhaseStatus\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.heist.PhaseStatus.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"extraMoney\x18\x03 \x01(\x05R\n" +
	"extraMoney\x12\x1c\n" +
	"\ttotalLoot\x18\x04 \x01(\x05R\ttotalLoot\"G\n" +
	"\x06Status\x12\x0e\n" +
	"\n" +
	"IN_PROGESS\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\v\n" +
	"\aFAILURE\x10\x02\x12\x13\n" +
	"\x0fAWAITING_ORDERS\x10\x03\"7\n" +
	"\x12DistractionDetails\x12!\n" +
	"\fturns_needed\x18\x01 \x01(\x05R\vturnsNeeded\"\x91\x01\n" +
	"\x13NotificationCommand\x12<\n" +
	"\acommand\x18\x01 \x01(\x0e2\".heist.NotificationCommand.CommandR\acommand\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\x05R\tfrequency\"\x1e\n" +
	"\aCommand\x12\t\n" +
	"\x05START\x10\x00\x12\b\n" +
	"\x04STOP\x10\x01\"C\n" +
	"\n" +
	"HitDetails\x12!\n" +
	"\fturns_needed\x18\x01 \x01(\x05R\vturnsNeeded\x12\x12\n" +
	"\x04loot\x18\x02 \x01(\x05R\x04loot\"B\n" +
	"\vLootDetails\x12\x12\n" +
	"\x04loot\x18\x01 \x01(\x05R\x04loot\x12\x1f\n" +
	"\vextra_money\x18\x02 \x01(\x05R\n" +
	"extraMoney\"d\n" +
	"\n" +
	"CutDetails\x12\x12\n" +
	"\x04loot\x18\x01 \x01(\x05R\x04loot\x12\x1f\n" +
	"\vextra_moeny\x18\x02 \x01(\x05R\n" +
	"extraMoeny\x12!\n" +
	"\freceived_cut\x18\x03 \x01(\x05R\vreceivedCut\"C\n" +
	"\x03Ack\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe8\x01\n" +
	"\rLesterService\x124\n" +
	"\x11ProposeHeistOffer\x12\f.heist.Empty\x1a\x11.heist.HeistOffer\x12.\n" +
	"\rDecideOnOffer\x12\x0f.heist.Decision\x1a\f.heist.Empty\x12D\n" +
	"\x18ManageStarsNotifications\x12\x1a.heist.NotificationCommand\x1a\f.heist.Empty\x12+\n" +
	"\n" +
	"ConfirmCut\x12\x11.heist.CutDetails\x1a\n" +
	".heist.Ack2\x96\x02\n" +
	"\x0fOperatorService\x12;\n" +
	"\x10StartDistraction\x12\x19.heist.DistractionDetails\x1a\f.heist.Empty\x12:\n" +
	"\x16CheckDistractionStatus\x12\f.heist.Empty\x1a\x12.heist.PhaseStatus\x12+\n" +
	"\bStartHit\x12\x11.heist.HitDetails\x1a\f.heist.Empty\x120\n" +
	"\fRetrieveLoot\x12\f.heist.Empty\x1a\x12.heist.LootDetails\x12+\n" +
	"\n" +
	"ConfirmCut\x12\x11.heist.CutDetails\x1a\n" +
	".heist.AckB\bZ\x06/protob\x06proto3"

var (
	file_proto_heist_proto_rawDescOnce sync.Once
	file_proto_heist_proto_rawDescData []byte
)

func file_proto_heist_proto_rawDescGZIP() []byte {
	file_proto_heist_proto_rawDescOnce.Do(func() {
		file_proto_heist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_heist_proto_rawDesc), len(file_proto_heist_proto_rawDesc)))
	})
	return file_proto_heist_proto_rawDescData
}

var file_proto_heist_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_heist_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_heist_proto_goTypes = []any{
	(PhaseStatus_Status)(0),          // 0: heist.PhaseStatus.Status
	(NotificationCommand_Command)(0), // 1: heist.NotificationCommand.Command
	(*Empty)(nil),                    // 2: heist.Empty
	(*HeistOffer)(nil),               // 3: heist.HeistOffer
	(*Decision)(nil),                 // 4: heist.Decision
	(*BasicMessage)(nil),             // 5: heist.BasicMessage
	(*PhaseResult)(nil),              // 6: heist.PhaseResult
	(*PhaseStatus)(nil),              // 7: heist.PhaseStatus
	(*DistractionDetails)(nil),       // 8: heist.DistractionDetails
	(*NotificationCommand)(nil),      // 9: heist.NotificationCommand
	(*HitDetails)(nil),               // 10: heist.HitDetails
	(*LootDetails)(nil),              // 11: heist.LootDetails
	(*CutDetails)(nil),               // 12: heist.CutDetails
	(*Ack)(nil),                      // 13: heist.Ack
}
var file_proto_heist_proto_depIdxs = []int32{
	0,  // 0: heist.PhaseStatus.status:type_name -> heist.PhaseStatus.Status
	1,  // 1: heist.NotificationCommand.command:type_name -> heist.NotificationCommand.Command
	2,  // 2: heist.LesterService.ProposeHeistOffer:input_type -> heist.Empty
	4,  // 3: heist.LesterService.DecideOnOffer:input_type -> heist.Decision
	9,  // 4: heist.LesterService.ManageStarsNotifications:input_type -> heist.NotificationCommand
	12, // 5: heist.LesterService.ConfirmCut:input_type -> heist.CutDetails
	8,  // 6: heist.OperatorService.StartDistraction:input_type -> heist.DistractionDetails
	2,  // 7: heist.OperatorService.CheckDistractionStatus:input_type -> heist.Empty
	10, // 8: heist.OperatorService.StartHit:input_type -> heist.HitDetails
	2,  // 9: heist.OperatorService.RetrieveLoot:input_type -> heist.Empty
	12, // 10: heist.OperatorService.ConfirmCut:input_type -> heist.CutDetails
	3,  // 11: heist.LesterService.ProposeHeistOffer:output_type -> heist.HeistOffer
	2,  // 12: heist.LesterService.DecideOnOffer:output_type -> heist.Empty
	2,  // 13: heist.LesterService.ManageStarsNotifications:output_type -> heist.Empty
	13, // 14: heist.LesterService.ConfirmCut:output_type -> heist.Ack
	2,  // 15: heist.OperatorService.StartDistraction:output_type -> heist.Empty
	7,  // 16: heist.OperatorService.CheckDistractionStatus:output_type -> heist.PhaseStatus
	2,  // 17: heist.OperatorService.StartHit:output_type -> heist.Empty
	11, // 18: heist.OperatorService.RetrieveLoot:output_type -> heist.LootDetails
	13, // 19: heist.OperatorService.ConfirmCut:output_type -> heist.Ack
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_heist_proto_init() }
func file_proto_heist_proto_init() {
	if File_proto_heist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_heist_proto_rawDesc), len(file_proto_heist_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_heist_proto_goTypes,
		DependencyIndexes: file_proto_heist_proto_depIdxs,
		EnumInfos:         file_proto_heist_proto_enumTypes,
		MessageInfos:      file_proto_heist_proto_msgTypes,
	}.Build()
	File_proto_heist_proto = out.File
	file_proto_heist_proto_goTypes = nil
	file_proto_heist_proto_depIdxs = nil
}
